# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49976f9ee381cdae9ebfa73cfd86291e"
name = "llms-demo"
handle = "llms-demo"
application_url = "https://investigate-protected-eve-turner.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://arrested-gathering-marketplace-k.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://arrested-gathering-marketplace-k.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_online_store_pages,read_product_listings,read_products"

[auth]
redirect_urls = ["https://investigate-protected-eve-turner.trycloudflare.com/auth/callback", "https://investigate-protected-eve-turner.trycloudflare.com/auth/shopify/callback", "https://investigate-protected-eve-turner.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
